pipeline {
     environment {
      JAVA_TOOL_OPTIONS = '-Duser.home=/root'
    }
    agent none
    stages {
        stage('Build Java') { 
            agent {
                docker {
                    image 'maven:3.9.0-eclipse-temurin-11' 
                    args '-v /var/jenkins_home:/root' 
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
        stage('Build Docker')

        {
            agent master 
            steps {
                sh """
                    docker build -t javaapp .
                """
            }
        }
        stage('Run')
        {
             agent master 
            steps {
                sh """
                    docker run javaapp
                """
            }
        }
    }
} 


