pipeline {
     environment {
      JAVA_TOOL_OPTIONS = '-Duser.home=/root'
    }
    agent none
    stages {
        stage('Build Java') { 
            agent {
                docker {
                    image 'maven:3.9.0-eclipse-temurin-11' 
                    args '-v /var/jenkins_home:/root' 
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
        // stage('Build Docker')
          
        // {
        //      agent {
        //            label 'master'
        //             }
        //     steps {
        //         sh """
        //             docker build -t 600694340247.dkr.ecr.eu-central-1.amazonaws.com/cicd-test:latest .
        //         """
        //     }
        //}
        // stage('Run')
        // {
        //     agent {
        //             label 'master'
        //        } 
        //     steps {
        //         sh """
        //             docker run javaapp
        //         """
        //     }
        // }
        stage('Build and Push')
        {
            agent {
                    label 'master'
               } 
            steps {
                script
                {
                    docker.withRegistry('600694340247.dkr.ecr.eu-central-1.amazonaws.com', 'ecr:eu-central-1:dft-dev') 
                    {
                        docker.build('cicd-test').push('latest')

                    }
                }
            }
        }
    }
} 

